"""Change cover field to store file path as string

Revision ID: 9b2afe3122d5
Revises: 
Create Date: 2025-07-23 22:00:33.427897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b2afe3122d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.alter_column('cover',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.alter_column('cover',
               existing_type=sa.String(length=300),
               type_=mysql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
